---
# K3s Server Arguments
k3s_server_args:
  - --disable traefik
  - --disable servicelb
  - --write-kubeconfig-mode 644
  - --cluster-cidr {{ cluster_cidr }}
  - --service-cidr {{ service_cidr }}
  - --node-name {{ inventory_hostname }}
  - --tls-san {{ ansible_host }}
