---
redis_namespace: "redis"
redis_image: "redis:7.2-alpine"
redis_password: "Redis@2026"
redis_cluster_replicas: 3
redis_pvc_size: "10Gi"
redis_storage_class: "longhorn"
redis_nodeport: 31379
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
