---
k3s_version: v1.30.3+k3s1
k3s_server_host: "{{ hostvars[groups['k3s_control'][0]]['ansible_host'] }}"
k3s_server_url: "https://{{ k3s_server_host }}:6443"
k3s_node_label: []
k3s_extra_agent_args: []
