---
- name: Cài K3s Control Plane
  hosts: k3s_control
  gather_facts: yes
  become: yes
  serial: 1
  roles:
    - k3s-server

  post_tasks:
    - name: Get cluster info
      command: /usr/local/bin/k3s kubectl cluster-info
      register: cluster_info
      changed_when: false

    - name: Display cluster info
      debug:
        var: cluster_info.stdout_lines
